# Generated by Django 5.2.2 on 2025-06-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='exercise_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
